apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "dentistry-registry.fullname" . }}-frontend
  labels:
    {{- include "dentistry-registry.labels" . | nindent 4 }}
spec:
  replicas: {{ .Values.frontend.replicaCount }}
  selector:
    matchLabels:
      app.kubernetes.io/name: {{ include "dentistry-registry.name" . }}-frontend
  template:
    metadata:
      labels:
        app.kubernetes.io/name: {{ include "dentistry-registry.name" . }}-frontend
        {{- include "dentistry-registry.labels" . | nindent 8 }}
    spec:
      containers:
        - name: frontend
          image: {{ printf "%s:%s" .Values.frontendImage.repository .Values.frontendImage.tag }}
          imagePullPolicy: {{ .Values.frontendImage.pullPolicy }}
          ports:
            - containerPort: {{ .Values.frontend.service.port }}
          env:
            - name: VITE_API_URL
              valueFrom:
                configMapKeyRef:
                  name: {{ include "dentistry-registry.fullname" . }}-frontend-config
                  key: VITE_API_URL
            - name: VITE_APP_NAME
              valueFrom:
                configMapKeyRef:
                  name: {{ include "dentistry-registry.fullname" . }}-frontend-config
                  key: VITE_APP_NAME
          resources: {{- toYaml .Values.frontend.resources | nindent 12 }}
---
apiVersion: v1
kind: Service
metadata:
  name: {{ include "dentistry-registry.fullname" . }}-frontend
  labels:
    {{- include "dentistry-registry.labels" . | nindent 4 }}
spec:
  type: {{ .Values.frontend.service.type }}
  ports:
    - port: {{ .Values.frontend.service.port }}
      targetPort: {{ .Values.frontend.service.port }}
      protocol: TCP
      name: http
  selector:
    app.kubernetes.io/name: {{ include "dentistry-registry.name" . }}-frontend
