apiVersion: v1
kind: Secret
metadata:
  name: {{ include "dentistry-registry.fullname" . }}-postgres
  labels:
    {{- include "dentistry-registry.labels" . | nindent 4 }}
type: Opaque
stringData:
  POSTGRES_USER: {{ .Values.postgres.user | quote }}
  POSTGRES_PASSWORD: {{ .Values.postgres.password | quote }}
  POSTGRES_DB: {{ .Values.postgres.database | quote }}
